---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v4.454.0 # renovate: depName=aquaproj/aqua-registry
  - name: local
    type: local
    path: experimental.yaml

packages:
  - name: ajeetdsouza/zoxide@v0.9.8
  - name: aquaproj/aqua-installer@v4.0.4
  - name: aquaproj/registry-tool@v0.3.6
  - name: aristocratos/btop@v1.4.6
  - name: astral-sh/uv@0.9.24
  - name: babarot/afx@v0.2.2
  - name: BurntSushi/ripgrep@15.1.0
  - name: cli/cli@v2.83.2
  - name: dandavison/delta@0.18.2
  - name: denoland/deno@v2.6.4
  - name: dylanaraps/neofetch@7.1.0
  - name: Enter-tainer/typstyle@v0.14.4
  - name: eza-community/eza@v0.23.4
  - name: golang.org/x/tools/gopls@v0.21.0
  - name: golang/go@go1.25.5
  - name: hadolint/hadolint@v2.14.0
  - name: hairyhenderson/gomplate@v4.3.3
  - name: high-moctane/mocword@v0.2.0
  - name: itchyny/gojq@v0.12.18
  - name: itchyny/mmv@v0.1.6
  - name: JohnnyMorganz/StyLua@v2.3.1
  - name: jqlang/jq@jq-1.8.1
  - name: junegunn/fzf/fzf-tmux@v0.67.0
  - name: junegunn/fzf@v0.67.0
  - name: k0kubun/xremap/x11@v0.16.6
  - name: ko1nksm/getoptions/gengetoptions@v3.3.2
  - name: ko1nksm/getoptions@v3.3.2
  - name: koalaman/shellcheck@v0.11.0
  - name: LuaLS/lua-language-server@3.16.4
  - name: mattn/efm-langserver@v0.0.54
  - name: mvdan/sh@v3.12.0
  - name: Myriad-Dreamin/tinymist@v0.14.8
  - name: nodejs/node@v25.2.1
  - name: oven-sh/bun@bun-v1.3.6
  - name: rhysd/actionlint@v1.7.10
  - name: rhysd/vim-startuptime@v1.3.2
  - name: sharkdp/bat@v0.26.1
  - name: sharkdp/fd@v10.3.0
  - name: sharkdp/hexyl@v0.16.0
  - name: sharkdp/hyperfine@v1.20.0
  - name: sharkdp/pastel@v0.11.0
  - name: tamasfe/taplo/full@0.9.3
  - name: TomWright/dasel@v3.2.1
  - name: tree-sitter/tree-sitter@v0.26.3
  - name: typst/typst@v0.14.2
  - name: x-motemen/ghq@v1.8.0
  - name: XAMPPRocky/tokei@v14.0.0
  - name: ziglang/zig@0.15.1

  # local registry
  - name: rrethy/hexokinase
    registry: local
    version: master
  - name: pipeseroni/pipes.sh@v1.3.0
    registry: local
