---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v4.319.1 # renovate: depName=aquaproj/aqua-registry
  - name: local
    type: local
    path: experimental.yaml

packages:
  - name: ajeetdsouza/zoxide@v0.9.7
  - name: aquaproj/aqua-installer@v3.1.1
  - name: aquaproj/registry-tool@v0.3.3
  - name: aristocratos/btop@v1.4.0
  - name: b3nj5m1n/xdg-ninja@v0.2.0.1
  - name: babarot/afx@v0.2.1
  - name: BurntSushi/ripgrep@14.1.1
  - name: charmbracelet/glow@v2.0.0
  - name: cli/cli@v2.67.0
  - name: dandavison/delta@0.18.2
  - name: denoland/deno@v2.2.1
  - name: dylanaraps/neofetch@7.1.0
  - name: Enter-tainer/typstyle@v0.13.0
  - name: eza-community/eza@v0.20.22
  - name: golang.org/x/tools/gopls@v0.18.0
  - name: golang/go@go1.24.0
  - name: hadolint/hadolint@v2.12.0
  - name: hairyhenderson/gomplate@v4.3.0
  - name: high-moctane/mocword@v0.2.0
  - name: itchyny/gojq@v0.12.17
  - name: itchyny/mmv@v0.1.6
  - name: JohnnyMorganz/StyLua@v2.0.2
  - name: jqlang/jq@jq-1.7.1
  - name: junegunn/fzf/fzf-tmux@v0.60.1
  - name: junegunn/fzf@v0.60.1
  - name: k0kubun/xremap/x11@v0.10.5
  - name: ko1nksm/getoptions/gengetoptions@v3.3.2
  - name: ko1nksm/getoptions@v3.3.2
  - name: koalaman/shellcheck@v0.10.0
  - name: LuaLS/lua-language-server@3.13.6
  - name: mattn/efm-langserver@v0.0.54
  - name: mvdan/sh@v3.10.0
  - name: Myriad-Dreamin/tinymist@v0.12.20
  - name: nametake/golangci-lint-langserver@v0.0.10
  - name: nektos/act@v0.2.74
  - name: noahgorstein/jqp@v0.7.0
  - name: nodejs/node@v23.8.0
  - name: oven-sh/bun@bun-v1.2.3
  - name: rhysd/actionlint@v1.7.7
  - name: rhysd/hgrep@v0.3.7
  - name: rhysd/vim-startuptime@v1.3.2
  - name: sharkdp/bat@v0.25.0
  - name: sharkdp/fd@v10.2.0
  - name: sharkdp/hexyl@v0.16.0
  - name: sharkdp/hyperfine@v1.19.0
  - name: sharkdp/pastel@v0.10.0
  - name: sheepla/longgopher@v0.0.3
  - name: simeji/jid@v0.7.6
  - name: tamasfe/taplo/full@0.9.3
  - name: TomWright/dasel@v2.8.1
  - name: tree-sitter/tree-sitter@v0.25.2
  - name: typst/typst@v0.13.0
  - name: x-motemen/ghq@v1.7.1
  - name: XAMPPRocky/tokei@v12.1.2
  - name: ziglang/zig@0.13.0

  # local registry
  - name: thinca/ciw
    registry: local
    version: master
  - name: machikado-network/sakura@v0.4.3
    registry: local
  - name: rrethy/hexokinase
    registry: local
    version: master
  - name: pipeseroni/pipes.sh@v1.3.0
    registry: local
